"""Build the reduced IEEE 33 augmented-matrix sparsity figure.

The original eight-panel sparsity figure remains generated by
``build_matrix_sparsity.py``. This script reads its retained matrix archive
and draws only the three matrices discussed in the manuscript.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import scienceplots  # noqa: F401
from build_matrix_sparsity import (
    DEFAULT_RELATIVE_THRESHOLD,
    PREVIEW_DPI,
    STYLE,
    draw_numerical_mask,
    numerical_mask,
)
from matplotlib.lines import Line2D
from matplotlib.patches import Patch

WORKFLOW_ROOT = Path(__file__).resolve().parent
DEFAULT_MATRIX_ARCHIVE = WORKFLOW_ROOT / "results" / "ieee33_wls_uq_matrices.npz"
FIGURE_STEM = "ieee33_augmented_matrix_sparsity"
FIGURE_SIZE = (7.16, 2.70)
PANEL_SPECS = (
    ("y_bus", r"(a) $\mathbf{Y}_{\mathrm{bus}}$", "Bus position"),
    ("augmented", r"(b) $\mathbf{A}$", "State--multiplier position"),
    ("augmented_ps", r"(c) $\mathbf{A}_{\mathrm{ps}}$", "Interleaved position"),
)


def load_selected_matrices(matrix_archive: Path) -> dict[str, np.ndarray]:
    """Load and validate the three matrices required by the reduced figure."""
    with np.load(matrix_archive) as archive:
        missing = {name for name, *_ in PANEL_SPECS}.difference(archive.files)
        if missing:
            raise ValueError(f"Matrix archive is missing: {', '.join(sorted(missing))}")
        matrices = {name: np.asarray(archive[name]) for name, *_ in PANEL_SPECS}

    n_bus = matrices["y_bus"].shape[0]
    if matrices["y_bus"].shape != (n_bus, n_bus):
        raise ValueError("Y_bus must be square")
    for name in ("augmented", "augmented_ps"):
        if matrices[name].shape != (2 * n_bus, 2 * n_bus):
            raise ValueError(f"{name} must have shape {(2 * n_bus, 2 * n_bus)}")
    return matrices


def build_figure(
    matrices: dict[str, np.ndarray],
    *,
    relative_threshold: float,
    output_root: Path,
) -> None:
    """Render the three-panel IEEE Transactions figure as PDF and PNG."""
    if not 0.0 <= relative_threshold < 1.0:
        raise ValueError("relative_threshold must lie in [0, 1)")

    n_bus = matrices["y_bus"].shape[0]
    with plt.style.context(STYLE), plt.rc_context({"savefig.bbox": None}):
        figure, axes = plt.subplots(1, 3, figsize=FIGURE_SIZE)
        for axis, (name, panel_label, axis_label) in zip(axes, PANEL_SPECS, strict=True):
            matrix = matrices[name]
            mask, _ = numerical_mask(matrix, relative_threshold)
            nonzeros = int(np.count_nonzero(mask))
            density = nonzeros / mask.size

            draw_numerical_mask(axis, mask)
            axis.text(0.0, 1.04, panel_label, transform=axis.transAxes, ha="left", va="bottom")
            axis.text(
                1.0,
                1.04,
                rf"$\mathrm{{nnz}}={nonzeros}$ ({100.0 * density:.1f}\%)",
                transform=axis.transAxes,
                ha="right",
                va="bottom",
                fontsize=7,
            )
            axis.set_xlabel(axis_label)
            axis.set_ylabel(axis_label)
            last_position = matrix.shape[0] - 1
            axis.set_xticks(sorted({0, last_position // 2, last_position}))
            axis.set_yticks(sorted({0, last_position // 2, last_position}))
            axis.tick_params(labelsize=7)
            if name == "augmented":
                axis.axhline(n_bus - 0.5, color="#D55E00", linewidth=0.55)
                axis.axvline(n_bus - 0.5, color="#D55E00", linewidth=0.55)

        figure.legend(
            handles=[
                Patch(facecolor="#3B0F70", edgecolor="black", linewidth=0.3, label="Numerical nonzero"),
                Patch(facecolor="white", edgecolor="black", linewidth=0.3, label="Numerical zero"),
                Line2D([0], [0], color="#D55E00", linewidth=0.7, label="State--multiplier boundary"),
            ],
            loc="lower center",
            ncol=3,
            fontsize=7,
            frameon=False,
        )
        figure.tight_layout(rect=(0.0, 0.13, 1.0, 0.90), pad=0.35, w_pad=0.75)
        figure_root = output_root / "figures"
        figure_root.mkdir(parents=True, exist_ok=True)
        figure.savefig(figure_root / f"{FIGURE_STEM}.pdf")
        figure.savefig(figure_root / f"{FIGURE_STEM}.png", dpi=PREVIEW_DPI)
        plt.close(figure)


def parse_args() -> argparse.Namespace:
    """Parse command-line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--matrix-archive",
        type=Path,
        default=DEFAULT_MATRIX_ARCHIVE,
        help="matrix archive produced by build_matrix_sparsity.py",
    )
    parser.add_argument(
        "--output-root",
        type=Path,
        default=WORKFLOW_ROOT,
        help="root receiving figures/ (default: this workflow directory)",
    )
    parser.add_argument(
        "--relative-threshold",
        type=float,
        default=DEFAULT_RELATIVE_THRESHOLD,
        help="relative cutoff tau in |M_ij| > tau ||M||_inf",
    )
    return parser.parse_args()


def main() -> None:
    """Build the reduced sparsity figure from the retained matrix archive."""
    args = parse_args()
    matrices = load_selected_matrices(args.matrix_archive)
    build_figure(matrices, relative_threshold=args.relative_threshold, output_root=args.output_root)
    print(f"Wrote {args.output_root / 'figures' / (FIGURE_STEM + '.pdf')}")
    print(f"Wrote {args.output_root / 'figures' / (FIGURE_STEM + '.png')}")
    print(f"Style: {STYLE}; figure size: {FIGURE_SIZE} in; PNG DPI: {PREVIEW_DPI}")


if __name__ == "__main__":
    main()
